#!/bin/bash

# Script para configurar DNS en Cloudflare para dona.sujeto10.com

echo "==================================="
echo "Configuración de DNS para DONA+"
echo "==================================="
echo ""

# Verificar que Vercel nos dio los valores DNS correctos
echo "📋 Obteniendo información DNS de Vercel..."
vercel domains inspect dona.sujeto10.com 2>/dev/null || true

echo ""
echo "==================================="
echo "📌 INSTRUCCIONES PARA CLOUDFLARE"
echo "==================================="
echo ""
echo "Necesitas configurar estos registros DNS en Cloudflare:"
echo ""
echo "Opción 1: CNAME (Recomendado)"
echo "--------------------------------"
echo "Tipo: CNAME"
echo "Nombre: dona"
echo "Destino: cname.vercel-dns.com"
echo "Proxy: ☁️ Desactivado (DNS only)"
echo ""
echo "Opción 2: A Record"
echo "--------------------------------"
echo "Tipo: A"
echo "Nombre: dona"
echo "Dirección IPv4: 76.76.21.21"
echo "Proxy: ☁️ Desactivado (DNS only)"
echo ""
echo "==================================="
echo "📱 PASOS EN CLOUDFLARE:"
echo "==================================="
echo ""
echo "1. Ve a https://dash.cloudflare.com"
echo "2. Selecciona el dominio 'sujeto10.com'"
echo "3. Ve a la sección DNS (en el menú lateral)"
echo "4. Click en '+ Add record'"
echo "5. Configura:"
echo "   - Type: CNAME"
echo "   - Name: dona"
echo "   - Target: cname.vercel-dns.com"
echo "   - Proxy status: DNS only (gris)"
echo "6. Click en 'Save'"
echo ""
echo "==================================="
echo "🔧 CONFIGURACIÓN CON CLOUDFLARE CLI"
echo "==================================="
echo ""
echo "Si tienes tu API Token de Cloudflare, puedes usar estos comandos:"
echo ""
echo "# Primero, configura tu token:"
echo "export CLOUDFLARE_API_TOKEN='tu-api-token-aqui'"
echo ""
echo "# Luego ejecuta:"
echo "curl -X POST \"https://api.cloudflare.com/client/v4/zones/ZONE_ID/dns_records\" \\"
echo "     -H \"Authorization: Bearer \$CLOUDFLARE_API_TOKEN\" \\"
echo "     -H \"Content-Type: application/json\" \\"
echo "     --data '{\"type\":\"CNAME\",\"name\":\"dona\",\"content\":\"cname.vercel-dns.com\",\"ttl\":1,\"proxied\":false}'"
echo ""
echo "==================================="
echo "✅ VERIFICACIÓN"
echo "==================================="
echo ""
echo "Después de configurar el DNS, verifica con:"
echo "1. nslookup dona.sujeto10.com"
echo "2. dig dona.sujeto10.com"
echo "3. En Vercel: vercel domains inspect dona.sujeto10.com"
echo ""
echo "La propagación DNS puede tomar hasta 48 horas, pero generalmente es inmediata con Cloudflare."
echo ""
echo "==================================="
echo "🌐 URLS DE TU APLICACIÓN"
echo "==================================="
echo ""
echo "✅ URL Temporal (Ya funciona): https://dona-ib4q1l3vf-nadalpiantini-fcbc2d66.vercel.app"
echo "⏳ URL Final (Después del DNS): https://dona.sujeto10.com"
echo ""